### ISSUE TITLE
No such file directory

### ISSUE THREAD

**Issue by jxtana** [Do0ks/Discord-Movie-Bot#3]
Hello can you help this i love your code work but i have problem
https://prnt.sc/AKHPEN0pTspZ

**Comment by Do0ks** [comment]
> 
> Hello can you help this i love your code work but i have problem
> https://prnt.sc/AKHPEN0pTspZ

It appears you may be pointing to the wrong directory or you don't have python properly installed. Please verify you have all the pre requirements installed and updated to the latest releases.

**Comment by jxtana** [comment]
i use https://replit.com/

**Comment by Do0ks** [comment]
please see 

https://github.com/Do0ks/Discord-Movie-Bot/blob/main/Revised-Plex-Bot.py

This is a revised code that doesn't require a docker and dotenv files. 

Also, I haven't tested this code outside a network, so it may not work considering the plex server is local.
