### ISSUE TITLE
Bot will not start 

### ISSUE THREAD

**Issue by HydracomServicesLTD** [Do0ks/Discord-Movie-Bot#5]
C:\Users\Administrator\Desktop\Discord-Movie-Bot-main>py Plex-Bot.py
|_____________Available clients on local network_____________|
|____________________________________________________________|
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Discord-Movie-Bot-main\Plex-Bot.py", line 58, in <module>
    if clients[0] != system:
       ~~~~~~~^^^
IndexError: list index out of range

**Comment by Do0ks** [comment]
please see 

https://github.com/Do0ks/Discord-Movie-Bot/blob/main/Revised-Plex-Bot.py

This is a revised code that doesn't require a docker and dotenv files. 
Let me know if you still have issues.
